version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysqlVolume:/var/lib/mysql
    networks:
      - mynet

  docker-python:
    build:
      context: .
    ports:
      - "3000:5000"
    networks:
      - mynet
    depends_on:
      - mysqldb

networks:
  mynet:

volumes:
  mysqlVolume: